### ISSUE TITLE
Your work is excellent! May I ask if you have encountered any network proxy errors when I am running it? How to solve it

### ISSUE THREAD

**Issue by xueshuo123** [eureka-research/eurekaverse#1]
(eurekaverse) xs-pc@xs-pc:~/下载/eurekaverse-main/eurekaverse$ python run_eurekaverse.py
ninja: no work to do.
Traceback (most recent call last):
  File "run_eurekaverse.py", line 41, in <module>
    from eurekaverse.utils.gpt_utils import prepare_prompts, query_gpt_initial, query_gpt_evolution, log_gpt_query
  File "/home/xs-pc/下载/eurekaverse-main/eurekaverse/utils/gpt_utils.py", line 28, in <module>
    client = OpenAI()
  File "/home/xs-pc/anaconda3/envs/eurekaverse/lib/python3.8/site-packages/openai/_client.py", line 123, in __init__
    super().__init__(
  File "/home/xs-pc/anaconda3/envs/eurekaverse/lib/python3.8/site-packages/openai/_base_client.py", line 857, in __init__
    self._client = http_client or SyncHttpxClientWrapper(
  File "/home/xs-pc/anaconda3/envs/eurekaverse/lib/python3.8/site-packages/openai/_base_client.py", line 755, in __init__
    super().__init__(**kwargs)
  File "/home/xs-pc/anaconda3/envs/eurekaverse/lib/python3.8/site-packages/httpx/_client.py", line 693, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
  File "/home/xs-pc/anaconda3/envs/eurekaverse/lib/python3.8/site-packages/httpx/_client.py", line 218, in _get_proxy_map
    return {
  File "/home/xs-pc/anaconda3/envs/eurekaverse/lib/python3.8/site-packages/httpx/_client.py", line 219, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/xs-pc/anaconda3/envs/eurekaverse/lib/python3.8/site-packages/httpx/_config.py", line 338, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7891/')

**Comment by johnny-wang16** [comment]
Hi there, thanks for reporting the issue. this doesn't seem to be an issue on our end and we havent met it before. Have u tried [this](https://github.com/lllyasviel/ControlNet/issues/182) tho?
